apiVersion: v1
kind: Service
metadata:
  name: inventory-management-system-app-service
  labels:
    app: inventory-management-system
spec:
  type: NodePort
  selector:
    app: inventory-management-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
